defmodule Dtn.Repo.Migrations.AddPrinted do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :printed, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:tasks) do
      remove :printed
    end
  end
end
