defmodule Dtn.Repo.Migrations.ReplaceImageWithType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:tasks), :image, to: :type
  end

  def down do
    rename table(:tasks), :type, to: :image
  end
end
